display_name: Harmony Music
package_name: harmonymusic
maintainer:
  name: northabyss
priority: optional
section: x11
installed_size: 20000
homepage: https://github.com/North-Abyss/Harmony-Music
description: A cross platform app for music streaming.
dependencies:
  - mpv
  - libmpv1 | libmpv2
  - libappindicator3-1 | libayatana-appindicator3-1

essential: false
icon: assets/icons/icon.png

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music